QueHacemos/jardinMvc/jardinMvc/Controllers/SubcategoriaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using jardinMvc.Context;
using System.Collections;

namespace jardinMvc.Controllers
{
    public class SubcategoriaController : Controller
    {
        private UnifyEntities db = new UnifyEntities();

        //
        // GET: /Subcategoria/

        public ActionResult Index()
        {
            var tbl_subcategoria = db.tbl_subcategoria.Include(t => t.tbl_categoria);
            return View(tbl_subcategoria.ToList());
        }

        //
        // GET: /Subcategoria/Details/5

        public ActionResult Details(int id = 0)
        {
            tbl_subcategoria tbl_subcategoria = db.tbl_subcategoria.Find(id);
            if (tbl_subcategoria == null)
            {
                return HttpNotFound();
            }
            return View(tbl_subcategoria);
        }

        //
        // GET: /Subcategoria/Create

        public ActionResult Create()
        {
            ViewBag.categoria_id = new SelectList(db.tbl_categoria, "categoria_id", "categoria_nombre");
            return View();
        }

        //
        // POST: /Subcategoria/Create

        [HttpPost]
        public ActionResult Create(tbl_subcategoria tbl_subcategoria)
        {
            if (ModelState.IsValid)
            {
                db.tbl_subcategoria.Add(tbl_subcategoria);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.categoria_id = new SelectList(db.tbl_categoria, "categoria_id", "categoria_nombre", tbl_subcategoria.categoria_id);
            return View(tbl_subcategoria);
        }

        //
        // GET: /Subcategoria/Edit/5

        public ActionResult Edit(int id = 0)
        {
            tbl_subcategoria tbl_subcategoria = db.tbl_subcategoria.Find(id);
            if (tbl_subcategoria == null)
            {
                return HttpNotFound();
            }
            ViewBag.categoria_id = new SelectList(db.tbl_categoria, "categoria_id", "categoria_nombre", tbl_subcategoria.categoria_id);
            return View(tbl_subcategoria);
        }

        //
        // POST: /Subcategoria/Edit/5

        [HttpPost]
        public ActionResult Edit(tbl_subcategoria tbl_subcategoria)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_subcategoria).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.categoria_id = new SelectList(db.tbl_categoria, "categoria_id", "categoria_nombre", tbl_subcategoria.categoria_id);
            return View(tbl_subcategoria);
        }

        //
        // GET: /Subcategoria/Delete/5

        public ActionResult Delete(int id = 0)
        {
            tbl_subcategoria tbl_subcategoria = db.tbl_subcategoria.Find(id);
            if (tbl_subcategoria == null)
            {
                return HttpNotFound();
            }
            return View(tbl_subcategoria);
        }

        //
        // POST: /Subcategoria/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_subcategoria tbl_subcategoria = db.tbl_subcategoria.Find(id);
            db.tbl_subcategoria.Remove(tbl_subcategoria);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public static IEnumerable SelectCategorias()
        {
            UnifyEntities db = new UnifyEntities();

            var select = from lista in db.tbl_categoria
                         select new { id = lista.categoria_id, nombre = lista.categoria_nombre };
            return select;
        }

        public ActionResult listadoSubcategorias(int categoria_id)
        {
            UnifyEntities entities = new UnifyEntities();

            var resultado = from lista in entities.tbl_subcategoria
                            where lista.categoria_id == categoria_id
                            select new { identificador = lista.subcategoria_id, nombre = lista.subcategoria_nombre };

            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

QueHacemos/jardinMvc/jardinMvc/Views/Subcategoria/Create.cshtml
@model jardinMvc.Context.tbl_subcategoria

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutWm.cshtml";
}

@section css
{
    <style>
        #content {
            padding-top: 45px !important;
        }
    </style>
    
}

<p class="lead">
    <span class="pink">Crear</span>
    <span class="pink">Registro</span>
</p>

@using (Html.BeginForm("Create", "Subcategoria", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    <fieldset>

        <div class="editor-label">
            @Html.Label("Categoría")
        </div>
        <div class="editor-field">
            @Html.DropDownList("categoria_id")
            @Html.ValidationMessageFor(model => model.categoria_id)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.subcategoria_nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.subcategoria_nombre)
            @Html.ValidationMessageFor(model => model.subcategoria_nombre)
        </div>

        <p>
            <input type="submit" class="btn btn-primary" value="Crear" />
            &nbsp;
            <input type="button" class="btn btn-primary" onclick="Regresar()" value="Regresar" />
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>

        $(document).ready(function () {
            $("#liSubcategorias").addClass("active");
        });

        function Regresar() {
            document.location = "../Subcategoria/Index"
        }

    </script>

}

QueHacemos/jardinMvc/jardinMvc/Views/Subcategoria/Delete.cshtml
@model jardinMvc.Context.tbl_subcategoria

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutWm.cshtml";
}

@section css
{
    <style>
        #content {
            padding-top: 45px !important;
        }
    </style>
    
}

<p class="lead">
    <span class="pink">Eliminar</span>
    <span class="pink">Registro</span>
</p>

<h4>Está seguro que desea eliminar ?</h4>
<fieldset>
    <div class="display-label">
        <h5>@Html.DisplayName("Categoría")</h5>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.tbl_categoria.categoria_nombre)
    </div>
    <br />
    <div class="display-label">
         <h5>@Html.DisplayNameFor(model => model.subcategoria_nombre)</h5>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.subcategoria_nombre)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <br />
    <p class="pMargin">
        <input type="submit" class="btn btn-primary" value="Eliminar" />
        &nbsp;
        <input type="button" class="btn btn-primary" onclick="Regresar()" value="Volver al Listado" />
    </p>
}
@section Scripts {

    <script>

        function Regresar() {
            document.location = "../Subcategoria"
        }

    </script>
}

QueHacemos/jardinMvc/jardinMvc/Views/Subcategoria/Details.cshtml
@model jardinMvc.Context.tbl_subcategoria

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<fieldset>
    <legend>tbl_subcategoria</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.subcategoria_id)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.subcategoria_id)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.subcategoria_nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.subcategoria_nombre)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.tbl_categoria.categoria_nombre)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.tbl_categoria.categoria_nombre)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Editar", "Edit", new { /* id=Model.PrimaryKey */ }) |
    @Html.ActionLink("Volver al listado", "Index")
</p>

QueHacemos/jardinMvc/jardinMvc/Views/Subcategoria/Edit.cshtml
@model jardinMvc.Context.tbl_subcategoria

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>tbl_subcategoria</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.subcategoria_id)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.subcategoria_id)
            @Html.ValidationMessageFor(model => model.subcategoria_id)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.subcategoria_nombre)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.subcategoria_nombre)
            @Html.ValidationMessageFor(model => model.subcategoria_nombre)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.categoria_id, "tbl_categoria")
        </div>
        <div class="editor-field">
            @Html.DropDownList("categoria_id", String.Empty)
            @Html.ValidationMessageFor(model => model.categoria_id)
        </div>

        <p>
            <input type="submit" value="Actualizar" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Volver al listado", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QueHacemos/jardinMvc/jardinMvc/Views/Subcategoria/Index.cshtml
@model IEnumerable<jardinMvc.Context.tbl_subcategoria>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutWm.cshtml";
}

@section nav 
{
    <nav class="profile">
        <div>
            <a href="/Empresa" class="rotate_index">
                <label>Empresas</label>
            </a>
            <a href="/Subcategoria" class="rotate_index">
                <label>Subcategorías</label></a>
        </div>
    </nav>
}

<p class="lead">
    <span class="pink">Administrar</span>
    <span class="pink">Subcategorías</span>
</p>


<div class="block">
    <div class="navbar navbar-inner block-header">
        <div class="muted pull-left">
            <br />
            <span>Categorías</span> &nbsp;&nbsp; @Html.DropDownList("idCategorias", new SelectList(jardinMvc.Controllers.SubcategoriaController.SelectCategorias(), "id", "nombre"))
        </div>
        <div class="pull-right">
            <span class="badge badge-info"></span>
        </div>
    </div>
    <div class="block-content collapse in">
        <table class="table table-striped" id="tblEstilo">
        </table>
        <p>
            <button type="button" class="btn btn-primary" onclick="Crear()">Crear</button>
        </p>
    </div>
</div>
@section Scripts {

    <script>

        $(document).ready(function () {
            $("#liSubcategorias").addClass("active");
        });

        function Crear() {
            document.location = "../Subcategoria/Create"
        }

        $("#idCategorias").ready(function () {

            var list = $('#idCategorias').val();
            var scntDiv = $("#tblEstilo");
            scntDiv.empty();
            $('<thead><tr><th>Nombre</th><th>Acción</th></tr></thead>').appendTo(scntDiv);

            $.getJSON("/Subcategoria/listadoSubcategorias", { categoria_id: list }, function (result) {
                $('<tbody>').appendTo(scntDiv);
                $.each(result, function (i, field) {
                    $('<tr><td>' + field.nombre + '</td><td><a href="/Subcategoria/Delete?id=' + field.identificador + '">Eliminar</a></td></tr>').appendTo(scntDiv);
                });
                $('</tbody>').appendTo(scntDiv);
            });
        });

        $("#idCategorias").change(function () {

            var list = $('#idCategorias').val();
            var scntDiv = $("#tblEstilo");
            scntDiv.empty();
            $('<thead><tr><th>Nombre</th><th>Acción</th></tr></thead>').appendTo(scntDiv);

            $.getJSON("/Subcategoria/listadoSubcategorias", { categoria_id: list }, function (result) {
                $('<tbody>').appendTo(scntDiv);
                $.each(result, function (i, field) {
                    $('<tr><td>' + field.nombre + '</td><td><a href="/Subcategoria/Delete?id=' + field.identificador + '">Eliminar</a></td></tr>').appendTo(scntDiv);
                });
                $('</tbody>').appendTo(scntDiv);
            });
        });

    </script>
}